[package]
name = "bind_test"
version = "0.1.0"
authors = ["Razvan Rotari <razvanrotari@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.1"
bind_lib = { path = "./src/bind_lib" }
